name: Deploy Github Pages

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "mkdocs.yml"
      - "requirements.txt"
  workflow_dispatch:
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade pip && pip install -r requirements.txt
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy